CREATE OR REPLACE FUNCTION ANALYTICS_CO2.NORMALIZE_CO2_UDF(
    CO2_PPM   NUMBER(35,4),
    MIN_CO2   NUMBER(35,4),
    MAX_CO2   NUMBER(35,4)
)
RETURNS NUMBER(35,4)
AS
$$
    CASE 
        WHEN MAX_CO2 = MIN_CO2 THEN 0.5
        ELSE ROUND((CO2_PPM - MIN_CO2) / (MAX_CO2 - MIN_CO2), 3)
    END
$$;
