name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - snowflake-snowpark-python
  - pip
  - openssl=1.1.1
  - pyarrow>=7.0.0
  - pyyaml
  - jinja2
  - boto3
  - cryptography
  - pytest  # Added directly as a conda package instead of pip package
  - pip:
    # Snowflake tools
    - snowflake-cli-labs
    - snowflake-connector-python>=3.0.0
    # Additional useful packages for data processing
    - pandas
    - numpy
    - pytest>=7.0.0  # Specify a version for consistency
    - python-dotenv
    - toml==0.10.2
    - typer==0.15.2
    - exceptiongroup>=1.2.2
    - iniconfig==2.0.0
    - tomli>=2.2.1
    - pytest-cov  # Add coverage reporting capability
