env: "dev"
database_name: "CO2_DB_DEV"
role_name: "CO2_ROLE_DEV"
warehouse_name: "CO2_WH_DEV"
warehouse_size: "XSMALL"
warehouse_suspend: 300
s3_url: "s3://noa-co2-datapipeline/noaa-co2-data/"
use_storage_integration: false
schemas:
  - "EXTERNAL"
  - "RAW_CO2"
  - "HARMONIZED_CO2"
  - "ANALYTICS_CO2"
  - "EXTERNAL"

# Task configuration
task_schedule: 'USING CRON 0 10 * * * UTC'  # Runs at 10 AM UTC daily
execute_tasks_immediately: true  # Set to false if you don't want to run tasks immediately

# Storage configuration
storage_integration_name: CO2_S3_INTEGRATION