env: "dev"
database_name: "CO2_DB_DEV"
role_name: "CO2_ROLE"
warehouse_name: "CO2_WH"
warehouse_size: "XSMALL"
warehouse_suspend: 300
s3_url: "s3://noa-co2-datapipeline/noaa-co2-data/"
use_storage_integration: false
schemas:
  - "EXTERNAL"
  - "RAW_CO2"
  - "HARMONIZED_CO2"
  - "ANALYTICS_CO2"