env: "prod"
database_name: "CO2_DB_PROD"
role_name: "CO2_ROLE"
warehouse_name: "CO2_WH"
warehouse_size: "MEDIUM"  # Larger size for production
warehouse_suspend: 600    # Longer auto-suspend time
s3_url: "s3://noa-co2-datapipeline/noaa-co2-data/"
use_storage_integration: true  # Use storage integration in production
storage_integration_name: "S3_CO2_INTEGRATION"
schemas:
  - "EXTERNAL"
  - "RAW_CO2"
  - "HARMONIZED_CO2"
  - "ANALYTICS_CO2"